django/sitewomen/users/urls.py
from django.urls import path, re_path, register_converter
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")), name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

django/sitewomen/women/urls.py
from django.urls import path, re_path, register_converter
from django.views.decorators.cache import cache_page

from . import views, converters

app_name = 'women'

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    path('', views.WomenHome.as_view(), name='home'),
    # path('', cache_page(30)(views.WomenHome.as_view()), name='home'),
    path('about/', views.about, name='about'),
    path('post/<int:pk>/', views.ShowPost.as_view(), name='post'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('edit/<int:pk>/', views.UpdatePage.as_view(), name='edit_page'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('delete/<slug:slug>/', views.DeletePage.as_view(), name='delete_page'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('login/', views.login, name='login'),
    path('category/<slug:cat_slug>/', views.WomenCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.WomenTag.as_view(), name='tag'),
    # path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag'),
    path("archive/<year4:year>/", views.archive, name='archive'),
    # re_path(r"^archive/(?P<year>[0-9]{4})/", views.archive),

]

django/sitewomen/women/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.contrib.auth import get_user_model
# from django.template.defaultfilters import slugify
from pytils.translit import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)


class Women(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True,
                            validators=[MinLengthValidator(5, message='Минимум 5 символов'),
                                        MaxLengthValidator(100, message='максимум 100 символов')])
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default=None,
                              blank=True, null=True, verbose_name='Фото')
    content = models.TextField(blank=True, verbose_name='Контент')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время обновления')
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                       default=Status.PUBLISHED, verbose_name='Статус')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True,
                            related_name='womens', verbose_name='Категории')
    tags = models.ManyToManyField('TagPosts', blank=True, related_name='womens', verbose_name='Теги')
    husband = models.OneToOneField('Husband', on_delete=models.SET_NULL,
                                   null=True, blank=True, related_name='women', verbose_name='Муж')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, related_name='posts', default=None)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    class Meta:
        # ordering = ['time_create']
        verbose_name = 'Знаменитые женщины'
        verbose_name_plural = 'Знаменитые женщины'


    def get_absolute_url(self):
        return reverse('women:post', kwargs={'post_slug': self.slug})
        # return reverse('women:post', args=(self.slug,))


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        # ordering = ['id']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.name}: {self.pk}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)



    def get_absolute_url(self):
        return reverse('women:category', kwargs={'cat_slug': self.slug})


class TagPosts(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)


    def __str__(self):
        return self.tag


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.tag)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('women:tag', kwargs={'tag_slug': self.slug})


class Husband(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    age = models.IntegerField(null=True, verbose_name='Возраст')
    m_count = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.name


class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model')

def read_qw(lst):
    for i, x in enumerate(lst):
        if i == 0:
            print(list(x.__dict__)[1:])
        print(list(x.__dict__.values())[1:])

django/sitewomen/women/views.py
import uuid
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.db.models import Prefetch
from  django.views import View
from  django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.template.loader import render_to_string


from women.forms import AddPostForm, UploadFileForm, ContactForm
from women.models import Women, Category, TagPosts, UploadFiles
from women.utils import DataMixin

menu = [{'title': "О сайте", 'url_name': 'women:about'},
        {'title': "Добавить статью", 'url_name': 'women:add_page'},
        {'title': "Обратная связь", 'url_name': 'women:contact'},
        {'title': "Войти", 'url_name': 'women:login'}
]


# def handle_uploaded_file(f):
#     with open(f"uploads/{f.name}", "wb+") as destination:
#         for chunk in f.chunks():
#             destination.write(chunk)


def handle_uploaded_file(f):
    name = f.name
    ext = ''

    if '.' in name:
        ext = name[name.rindex('.'):]
        name = name[:name.rindex('.')]

    suffix = str(uuid.uuid4())
    with open(f"uploads/{name}_{suffix}{ext}", "wb+") as destination:  #  файл не загружается, вероятно проблемма с правами доступа
        for chunk in f.chunks():
            destination.write(chunk)


# def index(request):
#     posts = Women.published.all().prefetch_related(Prefetch('cat', to_attr='category'))
#     # posts = Women.published.all().select_related('cat')
#     data = {'title': 'Главная страница',
#             'menu': menu,
#             'posts': posts,
#             'cat_selected': 0}
#     return render(request, 'women/index.html', context=data)
    # st = render_to_string('women/index.html')
    # return HttpResponse(st)

class WomenHome(DataMixin, ListView):
    # model = Women
    template_name = 'women/index.html'
    context_object_name = 'posts'
    title_page = 'Главная страница'
    cat_selected = 0
    # extra_context = {
    #         'title': 'Главная страница',
    #         'menu': menu,
    #         #  'posts': Women.published.all().prefetch_related(Prefetch('cat', to_attr='category')),
    #         'cat_selected': 0
    # }


    def get_queryset(self):
        w_lst = cache.get('women_posts')
        if not w_lst:
            w_lst = Women.published.all().prefetch_related(Prefetch('cat', to_attr='category'))
            cache.set('women_posts', w_lst, 30)
        return w_lst


class WomenCategory(DataMixin, ListView):
    template_name = 'women/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = context['posts'][0].cat
        return self.get_mixin_context(context,
                                      title='Категория - ' + cat.name,
                                      cat_selected=cat.pk)
        # context['title'] = 'Категория - ' + cat.name
        # context['menu'] = menu
        # context['cat_selected'] = cat.id
        # return context

    def get_queryset(self):
        return Women.published.filter(cat__slug=self.kwargs['cat_slug']).prefetch_related(Prefetch('cat', to_attr='category'))


class WomenTag(DataMixin, ListView):
    template_name = 'women/index.html'
    context_object_name = 'posts'
    allow_empty = True

    def get_queryset(self):
        tag = TagPosts.objects.filter(slug=self.kwargs['tag_slug']).first()  # get_object_or_404(TagPosts, slug=tag_slug)
        self.kwargs['tag_name'] = tag.tag
        return tag.womens.filter(is_published=Women.Status.PUBLISHED).prefetch_related('cat')


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title='Тег: ' + self.kwargs['tag_name'])
        # tag = self.kwargs['tag_slug']  # context['posts'][0].tags.all()[0]
        # context['title'] = 'Категория - ' + self.kwargs['tag_name']
        # context['menu'] = menu
        # context['cat_selected'] = None
        # return context


class ShowPost(DataMixin, DetailView):
    template_name = 'women/post.html'
    context_object_name = 'post'
    #  pk_url_kwarg = 'pk'
    slug_url_kwarg = 'post_slug'


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['title'] = context['post'].title
        return self.get_mixin_context(context, title = context['post'].title)

    def get_object(self, queryset=None):
        return get_object_or_404(Women.published, slug=self.kwargs[self.slug_url_kwarg])


class AddPage(PermissionRequiredMixin, LoginRequiredMixin, DataMixin, CreateView):
    template_name = 'women/addpage.html'
    form_class = AddPostForm
    title_page = 'Добавление страницы'
    permission_required = 'women.add_women'
    # model = Women
    # fields = ['title', 'slug', 'photo', 'content', 'cat', 'is_published', 'husband']
    # success_url = reverse_lazy('women:home')  маршрут определяется на основе метода get_absolute_url()
    # extra_context = {'title': 'Добавление страницы', 'menu': menu}

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class UpdatePage(PermissionRequiredMixin, DataMixin, UpdateView):
    template_name = 'women/addpage.html'
    model = Women
    fields = ['title', 'slug', 'photo', 'content', 'cat', 'is_published', 'husband']
    title_page = 'Редактирование статьи'
    permission_required = 'women.change_women'
    #  extra_context = {'title': 'Добавление страницы', 'menu': menu}
    #  success_url = reverse_lazy('women:home')

class DeletePage(DataMixin, DeleteView):
    template_name = 'women/deletepage.html'
    model = Women
    success_url = reverse_lazy('women:home')
    title_page = 'Удаление страницы'


@login_required
def about(request):
    contact_list = Women.published.all()
    paginator = Paginator(contact_list, 3)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    return render(request, 'women/about.html',
                  {'title': 'О сайте', 'page_object':  page_object})
    # if request.method == 'POST':
    #     form = UploadFileForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         # handle_uploaded_file(form.cleaned_data['file'])
    #         fr = UploadFiles(file=form.cleaned_data['file'])
    #         fr.save()
    # else:
    #     form = UploadFileForm()
    # return render(request, 'women/about.html', {'title': 'О сайте',
    #                                             'menu': menu, 'form': form})


# def show_post(request, post_slug):
#     post = get_object_or_404(Women, slug=post_slug)
#     data = {'title': post.title,
#             'menu': menu,
#             'post': post,
#             'cat_selected': None}
#     return render(request, 'women/post.html', context=data)

# def addpage(request):
#     if request.method == 'POST':
#         form = AddPostForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('women:home')
            # try:
            #     Women.objects.create(**form.cleaned_data)
            #     return redirect('women:home')
            # except:
            #     form.add_error(None, 'Ошибка добавления поста')
            # print(form.cleaned_data)

    # else:
    #     form = AddPostForm()
    # return render(request, 'women/addpage.html', context={'menu': menu,
    #                                             'title': 'Добавление страницы', 'form': form})


def login(request):
    return HttpResponse(f"<h2>Вход</h2>")


class ContactFormView(LoginRequiredMixin, DataMixin, FormView):
    form_class = ContactForm
    template_name = 'women/contact.html'
    success_url = reverse_lazy('women:home')
    title_page = "Обратная связь"

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


# @permission_required(perm='women.view_women', raise_exception=True)
# def contact(request):
#     return HttpResponse(f"<h2>Обратная связь</h2>")


# def show_category(request, cat_slug):
#     category = get_object_or_404(Category, slug=cat_slug)
#     data_db = Women.published.filter(cat_id=category.pk).select_related('cat')
#     data = {'title': f'Рубрика {category.name}',
#             'menu': menu,
#             'posts': data_db,
#             'cat_selected': category.pk}
#     return render(request, 'women/index.html', context=data)

# def show_tag_postlist(request, tag_slug):
#     tag = get_object_or_404(TagPosts, slug=tag_slug)
#     posts = tag.womens.filter(is_published=Women.Status.PUBLISHED).select_related('cat')
#     data = {
#         'title': f'Тег: {tag.tag}',
#         'menu': menu,
#         'posts': posts,
#         'cat_selected': None
#     }
#     return render(request, 'women/index.html', context=data)


def archive(request, year):
    if year > 2023:
        url1 = reverse('women:cats', args=('sport',))
        return redirect(url1)
    return HttpResponse(f"<h1>Архив по годам</h1><p>год: {year}</p>")


def page_not_found(request, exception):
    return HttpResponseNotFound(f"<h1>Страница не найдена</h1>")

django/sitewomen/women/templates/women/about.html
{%  extends 'base.html' %}

{%  block content  %}
<h1>  {{title}} </h1>

{% for item in page_object %}
<p> {{ item.pk }}: {{ item.title }} </p>
{% endfor %}

<nav  class="list-pages">
    <ul>
        {% for p in page_object.paginator.page_range %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>

{%  endblock %}

django/sitewomen/women/templates/women/addpage.html
{% extends 'base.html' %}

{% block content %}
    <h1> {{title}} </h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
       <p> <label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }} </label> {{ f }} </p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p> <button type="submit">Отправить</button></p>
    </form>
{% endblock %}

django/sitewomen/women/templates/women/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Отправить</button>
</form>

{% endblock %}

django/sitewomen/women/templates/women/deletepage.html
{% extends 'base.html' %}

{% block content %}
    <h1> {{title}} </h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        <p>Удаляемая запись: "{{ object }}"</p>
        {{ form.as_p }}
        <input type="submit" value="Удалить">
    </form>
{% endblock %}

django/sitewomen/women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
	<!-- {% if p.is_published %} -->
			<li>
				<div class="article-panel">
				<p class="first"> Категория: {{ p.category.name }} | автор: {{p.author.username|default:'автор неизвестен'}}</p>
				<p class="last"> Дата: {{ p.time_update|date:"d-m-Y H:i:s"}} </p>
				</div>
				{% if p.photo %}
                   <p ><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
				{% endif %}
				<h2>{{p.title}}</h2>
    <!-- {% autoescape off %} -->
	{{p.content|linebreaks|truncatewords:40}}
    <!-- {% endautoescape %} -->
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{p.get_absolute_url}}">Читать пост</a></p>
			</li>
	<!-- {% endif %} -->
	{% endfor %}
</ul>
{% endblock %}

{% block navigation %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
		{% if page_obj.has_previous %}
		<li class="page-num">
         <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
		</li>
{% endif %}
        {% for p in paginator.page_range %}
		{% if page_obj.number == p%}
		<li class="page-num page-num-selected">{{ p }}</li>
                   {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
		{% endif %}
        {% endfor %}
		{% if page_obj.has_next %}
		<li class="page-num">
         <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
		</li>
{% endif %}
    </ul>
	{% endif %}
</nav>
{% endblock %}

django/sitewomen/women/templates/women/list_categories.html
{% for cat in cats %}
{% if cat.id == cat_selected %}
    <li class="selected">{{ cat.name }}</li>
{% else %}
     <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
{% endif %}
{% endfor %}

django/sitewomen/women/templates/women/list_tags.html
{% if tags %}

<p> Теги </p>
<ul class="tags-list">
    {% for tag in tags %}
     <li ><a href="{{ tag.get_absolute_url }}">{{ tag.tag }}</a></li>
    {% endfor %}
</ul>

{% endif %}

django/sitewomen/women/templates/women/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
{% if perms.women.change_women %}
<p><a href="{% url 'women:edit_page' post.slug %}">Редактировать</a></p>
{% endif %}
    {% with post.tags.all as tags %}
    {% if tags %}
        <ul class="tags-list">
            <li>Теги:</li>
            {% for tag in tags %}
                <li ><a href="{{ tag.get_absolute_url }}">{{ tag.tag }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}
{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>

{% if post.photo %}
<p><IMG class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{ object.content|linebreaks }}

{% endblock %}